### PR TITLE
Updated fastify and other dependencies

### PR DESCRIPTION
**Pull request by afonsojramos**
I can't seem to be able to run tests.
But I don't think there should be any problem here.

### CODE REVIEW

**Comment by smartiniOnGitHub** [comment]
Hi, thanks for the PR, I'll try ASAP (and run tests), and tell you something ...

**Comment by smartiniOnGitHub** [comment]
To fix tests:
- edit `types/.eslintrc.json` and in "parserOptions" section, add as last option:
```
    "createDefaultProgram": true
```
- edit `package.json` and in the custom command "test:types", keep only "tsd" as command to run
- last, update some failing tests now ...
otherwise, tell me so I can do those changes, but you'll need to rebase your branch ... as you prefer.

If you want, update all dependencies to latest (or I'll do after this PR, no problem).

Tell me, if I can help. 
Thanks for now. Bye

**Comment by afonsojramos** [comment]
@smartiniOnGitHub your suggestion fixed the problems! Ended up updating other dependencies as well.

Typescript tests pass, however, there are some unit tests failing, related to code 503, however I don't think it is related to anything in this PR.

Have you thought of implementing GitHub Actions in this repository?

**Comment by smartiniOnGitHub** [comment]
Good news, I'll redo tests ASAP.
Yes I know that I need to enable GitHub Actions in the repo (it's only a problem due to lack of time) ...
I need to investigate for failing tests now, probably something has changed (not related to your PR).
Thanks for now.

**Comment by afonsojramos** [comment]
If you need any help let me know @smartiniOnGitHub, I'll be happy to help!

**Pull request merged**
